.github/workflows/pipeline.yml, composer.json, composer.lock, src/Message/MessageBag.php
=> ci: introduce github actions

examples/toolbox-clock.php, examples/toolbox-serpapi.php, examples/toolbox-weather.php, examples/toolbox-wikipedia.php, examples/toolbox-youtube.php, src/ToolBox/ToolAnalyzer.php
Not sure about this PR, maybe its better to be explicit?
WDYT? Feel free to close
=> Simplify constructing `ToolAnalyzer`

src/Message/MessageBag.php, tests/Message/MessageBagTest.php
Or what about naming it `merge()`?
=> Add `MessageBag::merge()` method

.github/workflows/pipeline.yml
No need to run cs-fixer, PHPStan etc. so often with different PHP versions
Needs
* #40
=> Split pipeline

composer.json
As we don't have support for it now
=> Remove suggestion

examples/chat-claude-anthropic.php, examples/chat-gpt-azure.php, examples/chat-gpt-openai.php, examples/embeddings-openai.php, examples/embeddings-voyage.php, examples/image-describer.php, examples/reasoning-openai.php, examples/structured-output-math.php, examples/toolbox-clock.php, examples/toolbox-serpapi.php, examples/toolbox-weather.php, examples/toolbox-wikipedia.php, examples/toolbox-youtube.php
WDYT?
```php
Running ./examples/chat-claude-anthropic.php...
Please set the ANTHROPIC_API_KEY environment variable.
Running ./examples/chat-gpt-azure.php...
Please set the AZURE_OPENAI_BASEURL, AZURE_OPENAI_DEPLOYMENT, AZURE_OPENAI_VERSION, and AZURE_OPENAI_KEY environment variables.
Running ./examples/chat-gpt-openai.php...
Ahoy, matey! Symfony be a treasure of a PHP framework, designed fer buildin' web applications and APIs faster than ye can say "shiver me timbers!" It be a robust, modular framework that helps developers create maintainable and scalable code, much like how a good pirate crew keeps their ship shipshape!
With Symfony, ye get a whole chest o' reusable components, which be like findin' a stash of gold doubloons. Ye can pick and choose what ye need fer yer project, whether …
```
=> Communicate what is needed to run an example

src/Document/Vector.php, src/Exception/DomainException.php, src/Exception/ExceptionInterface.php, src/Exception/InvalidArgumentException.php, src/Exception/InvalidToolImplementation.php, src/Exception/LogicException.php, src/Exception/MessageBagNotFound.php, src/Exception/MissingModelSupport.php, src/Exception/RuntimeException.php, src/OpenAI/Model/Gpt.php, src/OpenAI/Platform/AbstractPlatform.php, src/Response/Response.php, src/Store/MongoDB/Store.php, src/ToolBox/Tool/YouTubeTranscriber.php, src/ToolBox/ToolBox.php, tests/Response/ResponseTest.php
We should rely on our own exception classes
=> Clear exception hierachy

examples/structured-output-math.php, src/StructuredOutput/ResponseFormatFactory.php, src/StructuredOutput/SchemaFactory.php, tests/StructuredOutput/ResponseFormatFactoryTest.php, tests/StructuredOutput/SchemaFactoryTest.php
Or is there a reason for the factory method @chr-hertel ?
=> Simplify `SchemaFactory`

src/Store/Pinecone/Store.php
Feel free to close this PR @chr-hertel
=> Do not call `upsert()` with empty array

.env, examples/reasoning-openai.php, examples/structured-output-math.php
This reverts commit 4a48bc4f875f9de1aaa9e1d1016980b677eec7b1 and added checks via ENV var
Feel free to close
=> Revert "chore: remove reasoning example to safe my credit card (#116)"

example
didn't catch that i broke tool calling with streaming ... :(
=> feat: add verbose mode to example runner and extend error handling

src/OpenAI/Model/Gpt.php
=> fix: streamed tool call

README.md, examples/parallel-chat-gpt.php, examples/parallel-embeddings.php, src/Chain.php, src/Model/Response/AsyncResponse.php, src/Platform.php
hmm, that was somehow quite easy :)
=> feat: introducing async responses for parallel calling

src/Chain/ToolBox/ToolBox.php, tests/Chain/ToolBox/ToolBoxTest.php, tests/Fixture/Tool/ToolReturningArray.php, tests/Fixture/Tool/ToolReturningFloat.php, tests/Fixture/Tool/ToolReturningInteger.php, tests/Fixture/Tool/ToolReturningJsonSerializable.php, tests/Fixture/Tool/ToolReturningStringable.php
=> Handle `int`, `float`, `array`, `\Stringable` and `\JsonSerializable` return values from tools

composer.json, src/Model/Message/Role.php, tests/Model/Message/RoleTest.php
see https://github.com/OskarStark/enum-helper
=> Add `Comparable` trait from `oskarstark/enum-helper`

src/Chain.php
=> feat: override the chain's llm via option

examples/chat-system-prompt.php, src/Chain/InputProcessor/LlmOverrideInputProcessor.php, src/Chain/InputProcessor/SystemPromptInputProcessor.php, src/Exception/ToolBoxException.php, tests/Chain/InputProcessor/LlmOverrideInputProcessorTest.php, tests/Chain/InputProcessor/SystemPromptInputProcessorTest.php
Foundation for #171 - everything else need to go to the bundle i guess.
=> feat: add system prompt processor

src/Chain.php, src/Platform.php
Will keep that open until I have another debugging situation and will check how useful this idea is.
=> refactor: move error handling to chain + logging

src/Bridge/OpenAI/GPT.php
=> fix: gpt audio support

example
=> refactor: example runner to consume less vertical space

.env, README.md, examples/toolbox-tavily.php, src/Chain/ToolBox/Tool/Tavily.php
first rough integration to play around
https://tavily.com/
=> feat: add tavily tool support

README.md, src/Chain/ToolBox/ChainProcessor.php, tests/Chain/ToolBox/ChainProcessorTest.php
somehow this got lost with one refactoring ...
=> fix: re-enable filtering of tools

composer.json
Feel free to close, if you don't agree, no problem
=> Add Oskar as author

composer.json, src/Bridge/MongoDB/Store.php
=> [MongoDB] Do not use deprecated `selectCollection` method

phpstan.dist.neon, src/Bridge/Meta/LlamaPromptConverter.php, src/Bridge/MongoDB/Store.php, src/Chain/ToolBox/Attribute/ToolParameter.php, tests/Bridge/OpenAI/Embeddings/ResponseConverterTest.php
=> fix: phpstan 2.0 issues

.php-cs-fixer.dist.php, examples/chat-o1-openai.php, examples/stream-tools-gpt-openai.php, tests/Bridge/Meta/LlamaPromptConverterTest.php, tests/Bridge/OpenAI/Embeddings/ResponseConverterTest.php, tests/Chain/ToolBox/ParameterAnalyzerTest.php
See https://cs.symfony.com/doc/rules/whitespace/heredoc_indentation.html
This is the default value for this fixer
=> [PHP-CS-Fixer] Enable `heredoc_indentation` with `start_plus_one` rule

README.md, examples/store-mongodb-similarity-search.php, examples/store-pinecone-similarity-search.php, examples/stream-tools-gpt-openai.php, examples/structured-output-clock.php, examples/toolbox-clock.php, examples/toolbox-serpapi.php, examples/toolbox-tavily.php, examples/toolbox-weather-event.php, examples/toolbox-wikipedia.php, examples/toolbox-youtube.php, src/Chain/ToolBox/Tool/Clock.php, src/Chain/ToolBox/ToolBox.php
=> refactor: ease toolbox instatiation

src/Bridge/OpenAI/GPT.php
Adding the new GPT models
https://platform.openai.com/docs/models/gpt-4.1
https://platform.openai.com/docs/models/gpt-4.1-mini
https://platform.openai.com/docs/models/gpt-4.1-nano
=> feat: add new v4.1 models

composer.json
=> fix: youtube tool in dev examples

example
=> feat: allow filtering down of examples in runner

composer.json
cc @xabbuh, makes sense to add it back 👍
=> fix(mongodb-store): add back conflict
