php-llm/llm-chain

README.md
examples/chat-claude-anthropic.php
examples/chat-gpt-azure.php
examples/chat-gpt-openai.php
examples/structured-output-math.php
examples/toolbox-clock.php
examples/toolbox-serpapi.php
examples/toolbox-weather.php
examples/toolbox-wikipedia.php
examples/toolbox-youtube.php
src/Anthropic/ClaudePlatform.php
src/Anthropic/Model/Claude.php
src/Anthropic/Platform/Anthropic.php
src/OpenAI/Model/Embeddings.php
src/OpenAI/Model/Gpt.php
src/OpenAI/Platform.php
src/OpenAI/Platform/AbstractPlatform.php
src/OpenAI/Platform/Azure.php
src/OpenAI/Platform/OpenAI.php

Rename `Runtime` to `Platform`

---

src/StructuredOutput/SchemaFactory.php
tests/StructuredOutput/Data/User.php
tests/StructuredOutput/SchemaFactoryTest.php

Read description for schema to give more context to the LLM

---

examples/chat-gpt-openai.php
src/Anthropic/Model/Claude.php
src/OpenAI/Model/Gpt.php

Better options handling

---

examples/reasoning-openai.php

**Plan for the Directory Structure**
To build the Symfony application that meets the requirements, we'll structure the directories and files as follows:
- `src/`
- `Controller/`
- `QuestionController.php` - Handles the HTTP requests and responses.
- `Entity/`
- `Question.php` - The entity representing the question and answer.
- `Repository/`
- `QuestionRepository.php` - Custom repository for the `Question` entity.
- `Service/`
- `QuestionMatcher.php` - Contains the logic for matching questions.
- `templates/`
- `question/`
- `index.html.twig` - Template for the main question form and displaying answers.
- `ask.html.twig` - Template for asking the user to provide an answer.
- `config/`
- `packages/`
- `doctrine.yaml` - Database configuration (if not using `.env`).
- `routes.yaml` - Defines …

docs: add reasoning example

---

.github/workflows/pipeline.yml
README.md
composer.json
src/Store/MongoDB/Store.php

I need to test this in my project first
cc @alcaeus

Add MongoDB vector store

---

examples/structured-output-math.php
examples/toolbox-clock.php
examples/toolbox-serpapi.php
examples/toolbox-weather.php
examples/toolbox-wikipedia.php
examples/toolbox-youtube.php
src/Chain.php
src/Chain/Input.php
src/Chain/InputProcessor.php
src/Chain/Output.php
src/Chain/OutputProcessor.php
src/Exception/MissingModelSupport.php
src/OpenAI/Model/Gpt/Version.php
src/StructuredOutput/ChainProcessor.php
src/ToolBox/ChainProcessor.php

Idea to decouple functionality and extension points for chain - not working yet though
WDYT?

feat: introducing chain processors

---

.env
composer.json
examples/store-mongodb-similarity-search.php
src/Store/Azure/SearchStore.php
src/Store/InitializableStoreInterface.php
src/Store/MongoDB/Store.php

Initialize store

---

src/ToolBox/Attribute/ToolParameter.php
src/ToolBox/ParameterAnalyzer.php
tests/ToolBox/Attribute/ToolParameterTest.php
tests/ToolBox/ParameterAnalyzerTest.php
tests/ToolBox/Tool/ToolWithToolParameterAttribute.php

validate, that this is not allowed:
```php
#[ToolParameter(const: 'my-string')]
int $number
```

Add ability to describe tool parameters via `#[ToolParameter]` attribute

---

src/Exception/InvalidToolImplementation.php
src/ToolBox/Attribute/AsTool.php
src/ToolBox/Tool/Clock.php
src/ToolBox/Tool/OpenMeteo.php
src/ToolBox/Tool/SerpApi.php
src/ToolBox/Tool/SimilaritySearch.php
src/ToolBox/Tool/Wikipedia.php
src/ToolBox/Tool/YouTubeTranscriber.php
src/ToolBox/ToolAnalyzer.php
tests/ToolBox/ParameterAnalyzerTest.php
tests/ToolBox/Tool/ToolMultiple.php
tests/ToolBox/Tool/ToolNoParams.php
tests/ToolBox/Tool/ToolOptionalParam.php
tests/ToolBox/Tool/ToolRequiredParams.php
tests/ToolBox/Tool/ToolWithToolParameterAttribute.php
tests/ToolBox/ToolAnalyzerTest.php
tests/ToolBox/ToolBoxTest.php

Closes #82 
Heads up, BC incoming with the next release. @DZunke @OskarStark

refactor: introduce attribute namespace for `AsTool`

---

src/Message/Content/Content.php
src/Message/Content/Image.php
src/Message/Content/Text.php
src/Message/Message.php
src/Message/UserMessage.php

Extracted from
* https://github.com/php-llm/llm-chain/pull/92
I like it !

Rename `ContentInterface` to `Content`

---

Makefile
composer.json
example

feat: add example runner for parallel execution of examples

---

examples/stream-claude-anthropic.php
examples/stream-gpt-openai.php
src/Anthropic/Model/Claude.php
src/Anthropic/Platform.php
src/Anthropic/Platform/Anthropic.php
src/Chain/Output.php
src/LanguageModel.php
src/OpenAI/Model/Gpt.php
src/OpenAI/Platform.php
src/OpenAI/Platform/AbstractPlatform.php
src/OpenAI/Platform/Azure.php
src/OpenAI/Platform/OpenAI.php
src/Response/Response.php
src/Response/ResponseInterface.php
src/Response/StreamResponse.php
src/StructuredOutput/ChainProcessor.php

tough nut and still not happy with this implementation - feedback welcome
https://github.com/user-attachments/assets/c88c5bc2-0c93-401f-b95f-a659ebb35035

feat: support streaming of responses

---

src/Document/NullVector.php
src/Document/Vector.php
src/Document/VectorDocument.php
src/Document/VectorInterface.php
src/Store/Azure/SearchStore.php
tests/Document/NullVectorTest.php
tests/Document/VectorTest.php

If it is not available, `null` is an invalid type for our `vector property`

Introduce `NullVector` and `VectorInterface`

---

examples/structured-output-clock.php
src/Chain.php
src/Chain/ChainAwareProcessor.php
src/Chain/ChainAwareTrait.php
src/Chain/Output.php
src/Chain/OutputProcessor.php
src/StructuredOutput/ChainProcessor.php
src/ToolBox/ChainProcessor.php
tests/StructuredOutput/ChainProcessorTest.php

Changes:
* Processors can be `ChainAware` now and with that leverage other processors recursively.
* `SturcturedOutput\ChainProcessor` now also supports plain `response_format` and decodes it to an assoc array, see example and screenshot below
* Multiple `OutputProcessor` can interfere now on the same response => no weird return, but via `Output` instance

feat: introduce chain awareness in chain processors to nest them

---

src/Anthropic/Platform/Anthropic.php
src/OpenAI/Platform/Azure.php
src/OpenAI/Platform/OpenAI.php
src/Store/Azure/SearchStore.php
src/Voyage/Platform/Voyage.php

Remove superflous header

---

src/OpenAI/Platform/Azure.php
src/OpenAI/Platform/OpenAI.php

aka fail early
Feel free to close the PR

Argument validation in the constructor

---

src/Model/Language/Llama.php
tests/Model/Language/LlamaTest.php

Still untested 😄 
https://www.llama.com/docs/model-cards-and-prompt-formats/llama3_1/#-supported-roles-

LLama prompt

---

composer.json

There seem to be an error in the phpdocumentor of version 5.6 upwards which utilizes PHPStan phpdoc-parser in the fresh released version 2 and there is a compability problem. With 5.5 which does not allow the phpdoc-parser in v2 it is working as expected again. 
May need some time to do all the internal fixes before update.
See: 
```
There was 1 failure:
1) PhpLlm\LlmChain\Tests\StructuredOutput\ChainProcessorTest::processInputThrowsExceptionWhenLlmDoesNotSupportStructuredOutput
Failed asserting that exception of type "ArgumentCountError" matches expected exception "PhpLlm\LlmChain\Exception\MissingModelSupport". Message was: "Too few arguments to function PHPStan\PhpDocParser\Lexer\Lexer::__construct(), 0 passed in /home/runner/work/llm-chain/llm-chain/vendor/symfony/type-info/TypeResolve …
```

Conflict with PHPDocumentor higher then 5.5 because of doc parser bugs

---

src/Chain.php
src/ChainInterface.php

For simple mocks it would be cool to have the interface if the class is needed to be final and readonly as it is not a DTO but a service 😉 
Tests are failing cause of https://github.com/php-llm/llm-chain/pull/143

Add interface to final readonly chain for testability

---

src/ToolBox/ChainProcessor.php
tests/ToolBox/ChainProcessorTest.php

With the empty tools array in the request to Open AI the request is failing as a bad request. When the tool box is empty it should be ignored, even the processor is registered to the chain.

Fix empty tool list in request is ending in 400 bad request

---

src/ToolBox/ParameterAnalyzer.php
tests/ToolBox/ParameterAnalyzerTest.php

When utilizing single line comments the description of the argument in the toolbox contains `*/` of the closing comment. I have changed the regex to also have this supported. Also added new tests for the `ParameterAnalyzer` to check the parsing works as expected for different type of doc blocs.

Extend parameter description pattern to stop for single line comment

---

src/Bridge/OpenAI/Embeddings/ResponseConverter.php
tests/Bridge/OpenAI/Embeddings/ResponseConverterTest.php

When i request the embeddings with mutliple texts the response only contaion the first entry of the response. I did not really understand why it should be this way as the `VectorResponse` already supports having multiple vectors and so have adapted the response converter for the OpenAi Bridge embeddings. 
```php
$texts = array_fill(0, 20, 'Foo Bar Baz');
$vectors = $platform->request(new Embeddings(), $texts)->getContent();
```
The response of such a request, utilizing the OpenAI embeddings is an array with a single text or an array of text. So it does not change the current result of the `VectorResponse` for the user of the request.
Hope this fits?

Parse OpenAI response embedding to contain all embeddings

---

src/Bridge/Meta/LlamaPromptConverter.php
src/Chain/ToolBox/ChainProcessor.php
src/Model/Message/MessageBag.php
tests/Bridge/Meta/LlamaPromptConverterTest.php
tests/Model/Message/MessageBagTest.php

Follows
* https://github.com/php-llm/llm-chain/pull/166/files#r1898145794

[BC BREAK] `MessageBag` does not depend on `\ArrayObject` anymore

---

src/Model/Message/MessageBag.php

This is just an idea.
The `@final` that we don't cover BC and you extend on your own risk, that's how Symfony is doing such things.
I could then end up with just this to achieve my goals:
```php
<?php
declare(strict_types=1);
namespace App\Bridge\PhpLlm;
use PhpLlm\LlmChain\Model\Message\MessageBag;
use PhpLlm\LlmChain\Model\Message\MessageInterface;
final class EnhancedMessageBag extends MessageBag
{
public function __construct(MessageInterface ...$messages)
{
parent::__construct(...array_map([$this, 'wrap'], array_values($messages)));
}
public function add(MessageInterface $message): void
{
parent::add($this->wrap($message));
}
private function wrap(MessageInterface $message): MessageInterface
{
if ($message instanceof EnhancedMessage) {
return $message;
}
return new …
```

Unfinalize `MessageBag`

---

examples/image-generator-dall-e-2.php
examples/image-generator-dall-e-3.php

Within my PR #178 i had last changed the options within the examples but did not test them again. The plain option for the API is `model` and not `version` like in the `DallE` model class. So here the examples are fixed.

fix: Dall-E image generation examples

---

src/Bridge/OpenAI/GPT/ResponseConverter.php
src/Exception/ContentFilterException.php
src/Exception/ContentFilterViolationException.php

I am unsure about the logic, as this structure is only working for OpenAPI:
Any ideas @chr-hertel ?

Add possibility to react to content filter violation

---

src/Bridge/OpenAI/GPT/ResponseConverter.php
tests/Bridge/OpenAI/GPT/ResponseConverterTest.php

The reason is real https://community.openai.com/t/bug-in-api-response-finish-reason-field/287212 and is even mentioned here https://github.com/php-llm/llm-chain/blob/5da000ec0fb4fcc4d78399e40eac05506cfff6fc/src/Bridge/OpenAI/GPT/ResponseConverter.php#L159 Plus added some tests for the ResponseConverter

Fix: support finish reason "length"

---

examples/stream-tools-gpt-openai.php
src/Bridge/OpenAI/GPT/ResponseConverter.php
src/Chain/ToolBox/ChainProcessor.php
src/Chain/ToolBox/StreamResponse.php

**Please not merge! The changed code was just a wild guess ... read more below.**
I am currently experimenting a bit with the streamed responses from OpenAI gpt. First it worked like a charm but then i wanted to utilize my set of functions. Every request that should utilize those functions is not working anymore. I remembered there was the PR #126 that should have fixed it already. But this seem not to work. 
So i built the example `examples/stream-tools-gpt-openai.php` and found out it is not only not working for me but also not working for the library. Do you have any remembering on this topic @chr-hertel ? 
When i request a streamed response **without a function** call the first chunk looks like this
```
array:7 [
// ...
"choices" => array:1 [
0 => array:4 [
"index" => 0
"delta" => …
```

fix: GPT Streams with tool calls

---

src/Bridge/OpenAI/GPT/ResponseConverter.php

refactor: gpt stream conversion

---

README.md
src/Chain/ToolBox/Attribute/With.php
src/Chain/ToolBox/ParameterAnalyzer.php
src/Chain/ToolBox/Tool/OpenMeteo.php
tests/Chain/ToolBox/Attribute/ToolParameterTest.php
tests/Chain/ToolBox/ParameterAnalyzerTest.php
tests/Fixture/Tool/ToolWithToolParameterAttribute.php

Pulled out of #212 for a more neutral name also usable with DTO for structured output

refactor: rename tool param attribute

---

README.md

docs: better readability

---

src/Chain/ToolBox/Exception/ToolConfigurationException.php
src/Chain/ToolBox/MetadataFactory.php
src/Chain/ToolBox/MetadataFactory/ReflectionFactory.php
src/Chain/ToolBox/ToolBox.php
tests/Chain/ToolBox/MetadataFactory/ReflectionFactoryTest.php
tests/Chain/ToolBox/ToolBoxTest.php

Preparation for different tool metadata sources, e.g. config or mcp based

refactor: introduce tool metadata factory interface

---

src/Chain/ToolBox/ToolResultConverter.php
tests/Chain/ToolBox/ToolResultConverterTest.php

Breaking Change by limiting the tool result from `mixed` to actually supported types.

fix: handle void|null tool response graceful

---

src/Chain/ToolBox/Exception/ToolNotFoundException.php
src/Chain/ToolBox/ExecutionReference.php
src/Chain/ToolBox/Metadata.php
src/Chain/ToolBox/MetadataFactory/ReflectionFactory.php
src/Chain/ToolBox/ToolBox.php
tests/Chain/InputProcessor/SystemPromptInputProcessorTest.php
tests/Chain/ToolBox/ChainProcessorTest.php
tests/Chain/ToolBox/FaultTolerantToolBoxTest.php
tests/Chain/ToolBox/MetadataFactory/ReflectionFactoryTest.php

replaces #255 if successful
motivation: the execution reference is a pointer what the toolbox needs to execute. classname + method is only one type - with MCP it could also be a server + toolname.

refactor: introduce execution reference in tool metadata

---

src/Chain/ToolBox/Exception/ToolConfigurationException.php
src/Chain/ToolBox/Exception/ToolMetadataException.php
src/Chain/ToolBox/MetadataFactory.php
src/Chain/ToolBox/MetadataFactory/AbstractFactory.php
src/Chain/ToolBox/MetadataFactory/ChainFactory.php
src/Chain/ToolBox/MetadataFactory/MemoryFactory.php
src/Chain/ToolBox/MetadataFactory/ReflectionFactory.php
tests/Chain/InputProcessor/SystemPromptInputProcessorTest.php
tests/Chain/ToolBox/MetadataFactory/ChainFactoryTest.php
tests/Chain/ToolBox/MetadataFactory/MemoryFactoryTest.php
tests/Chain/ToolBox/MetadataFactory/ReflectionFactoryTest.php
tests/Chain/ToolBox/ToolBoxTest.php
tests/Fixture/Tool/ToolNoAttribute1.php
tests/Fixture/Tool/ToolNoAttribute2.php

* allows to use tools without attributes, but still leverages reflection for parameters
* allows to override tools configured with attributes with an explicit config
closes #134 & replaces #160
foundation for using third party classes as tools and registering tools dynamically via MCP

feat: introduce chain and memory tool metadata factory

---

src/Bridge/Anthropic/Claude.php
src/Bridge/Anthropic/ModelHandler.php

I have added Anthropic tool use support but I cannot figure out how to preserve text content that is sent with tool use request. I have tried to copy OpenAI function calling but that seems to loose text content during function call too.

feat: add support for Anthropic tool use

---

.github/workflows/pipeline.yml

I think it's annoying to only see other tests if the commit message matches the format - besides the feedback, it's a good reminder for me to override the commit message while merging, but i want to have the results of other qa tests at hand than.

ci: reorder qa pipeline to shift commit check to last step

---

.github/workflows/pipeline.yml

For now the easiest solution as the pipeline doesn't need the extension anyways.

ci: skip mongodb extension for now

---

examples/chat-claude-anthropic.php
examples/chat-llama-azure.php
examples/image-generator-dall-e-3.php
src/Bridge/Anthropic/Claude.php
src/Bridge/Anthropic/ModelHandler.php
src/Bridge/Azure/Meta/LlamaHandler.php
src/Bridge/Azure/OpenAI/EmbeddingsModelClient.php
src/Bridge/Azure/OpenAI/GPTModelClient.php
src/Bridge/Azure/OpenAI/WhisperModelClient.php
src/Bridge/Google/Gemini.php
src/Bridge/Google/ModelHandler.php
src/Bridge/Meta/Llama.php
src/Bridge/Ollama/LlamaModelHandler.php
src/Bridge/OpenAI/DallE.php
src/Bridge/OpenAI/DallE/ModelClient.php
src/Bridge/OpenAI/Embeddings.php
src/Bridge/OpenAI/Embeddings/ModelClient.php
src/Bridge/OpenAI/GPT.php
src/Bridge/OpenAI/GPT/ModelClient.php
src/Bridge/OpenAI/Whisper.php
src/Bridge/OpenAI/Whisper/ModelClient.php
src/Bridge/OpenRouter/Client.php
src/Bridge/OpenRouter/GenericModel.php
src/Bridge/Replicate/LlamaModelClient.php
src/Bridge/Voyage/ModelHandler.php
src/Bridge/Voyage/Voyage.php
src/Model/Model.php
tests/Bridge/OpenAI/DallETest.php

I'm currently working on an integration for Hugging Face and I think `$version` is misleading since this could also use quite different Models of one family.
Looking more into the direction of `GenericModel` what we saw already with #203 
https://github.com/php-llm/llm-chain/blob/main/src/Bridge/OpenRouter/GenericModel.php
WDYT @OskarStark @DZunke

refactor: rename Model::version to Model::name

---

.gitignore
README.md
composer.json
examples/transformers-text-generation.php
src/Bridge/TransformersPHP/Handler.php
src/Bridge/TransformersPHP/Model.php
src/Bridge/TransformersPHP/PipelineResponse.php
src/Bridge/TransformersPHP/PlatformFactory.php

Sitting on top of https://github.com/CodeWithKyrian/transformers-php

feat: add support for TransformersPHP for model runtime in PHP

---

examples/chat-gpt-openai-metadata.php
src/Bridge/OpenAI/DallE/ImageResponse.php
src/Bridge/OpenAI/TokenOutputProcessor.php
src/Chain/Toolbox/StreamResponse.php
src/Model/Response/AsyncResponse.php
src/Model/Response/BaseResponse.php
src/Model/Response/BinaryResponse.php
src/Model/Response/ChoiceResponse.php
src/Model/Response/Exception/RawResponseAlreadySet.php
src/Model/Response/Metadata/Metadata.php
src/Model/Response/Metadata/MetadataAwareTrait.php
src/Model/Response/RawResponseAwareTrait.php
src/Model/Response/ResponseInterface.php
src/Model/Response/StreamResponse.php
src/Model/Response/StructuredResponse.php
src/Model/Response/TextResponse.php
src/Model/Response/ToolCallResponse.php
src/Model/Response/VectorResponse.php
tests/Bridge/OpenAI/TokenOutputProcessorTest.php
tests/Model/Response/AsyncResponseTest.php
tests/Model/Response/BaseResponseTest.php
tests/Model/Response/Exception/RawResponseAlreadySetTest.php
tests/Model/Response/Metadata/MetadataAwareTraitTest.php
tests/Model/Response/Metadata/MetadataTest.php
tests/Model/Response/RawResponseAwareTraitTest.php

Currently it is not really possible to get into details of the interaction between user and model because the HTTPResponse is hidden behind the response converter and is then forgotten forever. So the only possibility currently to get details from the interaction would be a custom response and a custom response converter. 
As a draft and to collect your ideas and other input i want to throw this stone into the lake with having the HTTPResponse also transported into the direction of the output processors. Could this give a bit more flexibility? What do you think? 
Please have in mind this is only a draft to discuss. I thought about having this also possible if a request fails with an error status code in the future so the output processors could handle in a separation of convern way if …

feat: Add Raw Response Metadata Handling - GPT Token Usage Example

---

src/Bridge/Pinecone/Store.php

When adding documents, it does not take configured namespace into consideration, this PR fixes it.

fix: missing namespace when upserting in Pinecone store

---

src/Bridge/Anthropic/ModelHandler.php
tests/Bridge/Anthropic/ModelHandlerTest.php

fix: flaky anthropic tool calls with empty text

---

README.md
src/Chain/Toolbox/ChainProcessor.php
tests/Chain/Toolbox/ChainProcessorTest.php

Adds an option to the Toolbox/ChainProcessor to keep tool messages by avoiding to clone the original messageBag
Fixes #321

feat: add option to keep tool messages

---

composer.json

test: to mock the ChainInterface we need to skip broken PHPUnit versions

---

examples/google/toolcall.php
src/Platform/Bridge/Google/Contract/AssistantMessageNormalizer.php
src/Platform/Bridge/Google/Contract/ToolCallMessageNormalizer.php
src/Platform/Bridge/Google/Contract/ToolNormalizer.php
src/Platform/Bridge/Google/Gemini.php
src/Platform/Bridge/Google/ModelHandler.php
src/Platform/Bridge/Google/PlatformFactory.php
tests/Platform/Bridge/Google/Contract/AssistantMessageNormalizerTest.php
tests/Platform/Bridge/Google/Contract/ToolCallMessageNormalizerTest.php
tests/Platform/Bridge/Google/Contract/ToolNormalizerTest.php

Add tool support to Google Gemini.
Extracted from #320 with updates after #326

Google Gemini tool support

---

.github/workflows/pipeline.yml
composer.json

closes #286
partially reverts #281

Allow mongodb/mongodb 2.0

---

.env
compose.yaml
composer.json
examples/store/mariadb-similarity-search.php
src/Store/Bridge/MariaDB/Store.php

feat: add MariaDB store

---

src/Store/Bridge/MariaDB/Store.php

MariaDB insists the dimensions of the vector being inserted match exactly the dimensions of the vector defined in the schema.
Since the store knows nothing about the Model & it's expected vector dimensions, let's allow passing vector dimensions as a parameter to `initialize()` leave the problem to the user.

chore: Allow arbitrary vector dimensions for MariaDB store

---

examples/store/mariadb-similarity-search-gemini.php
src/Platform/Bridge/Google/Embeddings.php
src/Platform/Bridge/Google/Embeddings/ModelClient.php
src/Platform/Bridge/Google/Embeddings/TaskType.php
src/Platform/Bridge/Google/PlatformFactory.php
src/Platform/ModelClientInterface.php
tests/Platform/Bridge/Google/Embeddings/EmbeddingsModelClientTest.php

Add Embeddings support for Google Gemini.
Only batch embedding implemented.
Related to #28

feat: Add Gemini Embeddings

---

src/Chain/Toolbox/ToolResultConverter.php
tests/Chain/Toolbox/ToolResultConverterTest.php

feat: Allow any normalizable result from a tool

---

examples/google/server-tools.php
src/Platform/Bridge/Google/ModelHandler.php
src/Platform/Contract.php

Add support for Google server-side tools like [Google search](https://ai.google.dev/gemini-api/docs/google-search), [URL context](https://ai.google.dev/gemini-api/docs/url-context) & [Code execution](https://ai.google.dev/gemini-api/docs/code-execution)
---
I thought of using `Tool` classes for this but didn't find any solution I was happy with, so went the easy way for now.
Ideally no changes would've been required for this approach at all, but there were 2 issues:
1. Gemini API insist on providing empty object, and IMO it's not feasible to expect end-user to provide `new \ArrayObject()`
2. If you provide `tools` in `call`'s `$options`, then all toolbox tools go away – hence the new `server_tools` _(open to better naming – `remote_tools`?)_
---
If someone has already given this a …

feat: Google Gemini server tools

---

src/Chain/Toolbox/Event/ToolCallArgumentsResolved.php
src/Chain/Toolbox/ToolCallArgumentResolver.php
src/Chain/Toolbox/ToolCallArgumentResolverInterface.php
src/Chain/Toolbox/Toolbox.php
tests/Chain/Toolbox/ToolCallArgumentResolverTest.php
tests/Chain/Toolbox/ToolboxTest.php
tests/Fixture/Tool/ToolDate.php

feat: Denormalize tool arguments

---

src/Chain/Toolbox/ToolCallArgumentResolver.php
tests/Chain/Toolbox/ToolCallArgumentResolverTest.php
tests/Fixture/Tool/ToolArray.php

@valtzu any idea about this case?
found it after merging #359 with example [examples/toolbox/tavily.php](https://github.com/php-llm/llm-chain/blob/main/examples/toolbox/tavily.php)
patch feels a bit hacky, but does the job atm

fix: resolve array tool arguments

---

.env
examples/google/audio-input.php
examples/google/chat.php
examples/google/image-input.php
examples/google/pdf-input-binary.php
examples/google/server-tools.php
examples/google/stream.php
examples/google/structured-output-clock.php
examples/google/structured-output-math.php
examples/google/toolcall.php
examples/store/mariadb-similarity-search-gemini.php

refactor: rename `GOOGLE_API_KEY` to `GEMINI_API_KEY`

---

src/Platform/Contract.php
tests/Platform/ContractTest.php

As brought up in #371 it could be a possible extension point to the contract to reintroduce the support for `JsonSerializable` objects when there are no normalizers for an object. 
So it would be a possible alternative for custom `MessageBagInterface`, `MessageInterface`, `ContentInterface`, etc. by allowing them to implement the `JsonSerializable` interface.

feat: allow JsonSerializable objects in contract

---

src/Platform/Bridge/Google/Contract/ToolNormalizer.php
src/Platform/Bridge/Google/ModelHandler.php
tests/Platform/Bridge/Google/Contract/ToolNormalizerTest.php

fix: Gemini multiple tools

---

composer.json
src/Chain/Chat/MessageStore/CacheStore.php
src/Chain/Chat/MessageStore/SessionStore.php
src/Chain/Toolbox/Tool/Crawler.php
src/Chain/Toolbox/Tool/YouTubeTranscriber.php
src/Platform/Bridge/Bedrock/PlatformFactory.php
src/Platform/Bridge/TransformersPHP/PlatformFactory.php
src/Store/Bridge/ChromaDB/Store.php
src/Store/Bridge/MariaDB/Store.php
src/Store/Bridge/MongoDB/Store.php
src/Store/Bridge/Pinecone/Store.php

Remove the `suggest` section from composer.json and add explicit runtime checks
that throw exceptions with helpful composer require commands when optional
dependencies are missing.
This provides better developer experience by:
- Giving clear error messages when optional dependencies are needed
- Providing the exact composer command to install missing packages
- Following Symfony's pattern for handling optional dependencies
Optional dependencies now throw exceptions instead of
silently failing when the required packages are not installed.

refactor: replace composer suggests with runtime checks

---

phpstan.dist.neon

This PR updates the PHPStan configuration to use an error identifier instead of a regex pattern for ignoring array type errors in tests.
- Replace regex pattern  with identifier 
Using error identifiers is the recommended approach because:
- **More stable**: Identifiers don't change across PHPStan versions, unlike error message text
- **Cleaner**: Easier to read and understand the intent
- **Maintainable**: Less prone to breaking if error message wording changes
PHPStan analysis passes with the new configuration.

chore: use PHPStan error identifier instead of regex pattern

---

src/Platform/Message/AssistantMessage.php
src/Platform/Message/MessageInterface.php
src/Platform/Message/SystemMessage.php
src/Platform/Message/ToolCallMessage.php
src/Platform/Message/UserMessage.php
tests/Platform/ContractTest.php
tests/Platform/Message/AssistantMessageTest.php
tests/Platform/Message/SystemMessageTest.php
tests/Platform/Message/ToolCallMessageTest.php
tests/Platform/Message/UserMessageTest.php

This PR updates the message ID type from `TimeBasedUidInterface` to `AbstractUid&TimeBasedUidInterface` using PHP's intersection types. This change provides more flexibility while maintaining type safety.
Using the intersection type `AbstractUid&TimeBasedUidInterface` ensures that:
- ✅ Both `toRfc4122()` (from AbstractUid) and `getDateTime()` (from TimeBasedUidInterface) are available
- ✅ Implementations can use any time-based UID type (UUID v1/v6/v7 or ULID)
- ✅ Type safety is maintained
- ✅ All existing tests pass without modification
- Updated `MessageInterface::getId()` return type
- Updated all message implementations (AssistantMessage, SystemMessage, UserMessage, ToolCallMessage)
- Updated anonymous class in tests
1. **Flexibility**: Users can now implement messages with either UUID …

feat: use intersection type `AbstractUid&TimeBasedUidInterface` for flexible message IDs
